"""
Score usernames for political leaning.
-1 = liberal, 1 = conservative, 0 = neutral
The vast majority of usernames will be 0.

Script generated by Claude Opus 4.6
"""

import re
import csv
import sys

# (pattern, score) — all matched against lowercased username
# Scores > 0 = conservative, < 0 = liberal
KEYWORD_RULES: list[tuple[str, float]] = [
    # Strong conservative signals
    (r"trump(?!et)", 0.4),          # avoid "trumpet"; lowered — bare "trump" is ambiguous (supporters AND detractors use it)
    (r"(?<![a-z])maga", 0.95),      # avoid embedded: "jeffmagadia", "womenzillamagazine"
    (r"(?<![a-z])magaa+", 0.95),
    (r"kag\b", 0.9),          # Keep America Great
    (r"deplorable", 0.85),
    (r"qanon", 0.95),
    (r"wwg1wga", 0.95),
    (r"\bnra\b", 0.8),              # avoid "farhanrahee" etc.
    (r"2adefend", 0.85),
    (r"reagan", 0.8),
    (r"hannity", 0.85),
    (r"tucker_?carlson", 0.85),     # avoid bare "tucker" (common first name)
    (r"rushbaugh", 0.85),
    (r"limbaugh", 0.85),
    (r"gop_", 0.8),
    (r"_gop", 0.8),
    (r"gopvoter", 0.8),
    (r"republican", 0.75),
    (r"conservativ", 0.75),
    (r"tradcon", 0.8),
    (r"patriot\d", 0.5),       # patriot + digits often political
    (r"ultra_?maga", 0.95),
    (r"ultra_?patriot", 0.8),
    (r"god_?guns_?trump", 0.95),
    (r"freedomloving", 0.7),
    (r"freedomfighter", 0.6),
    (r"taxenou", 0.5),
    (r"taxed_?enough", 0.7),
    (r"teaparty", 0.8),
    (r"tea_party", 0.8),
    (r"rightwin", 0.8),
    (r"right_?wing", 0.8),
    (r"alt_?right", 0.85),
    (r"altright", 0.85),
    (r"red_?pilled", 0.85),
    (r"redpilled", 0.85),
    (r"redpill", 0.8),
    (r"infowars", 0.85),
    (r"alex_?jones", 0.8),
    (r"proudboy", 0.9),
    (r"proud_?boy", 0.9),
    (r"boogaloo", 0.85),
    (r"militia", 0.6),
    (r"molon_?labe", 0.85),
    (r"threepercent", 0.85),
    (r"3percent", 0.85),
    (r"oathkeeper", 0.8),
    (r"oath_?keep", 0.8),
    (r"foxnews", 0.65),
    (r"breitbart", 0.8),
    (r"dailywire", 0.75),
    (r"ben_?shapiro", 0.8),
    (r"candace_?owens", 0.8),
    (r"dennis_?prager", 0.8),
    (r"prager_?u", 0.75),
    (r"tpusa", 0.8),           # Turning Point USA
    (r"turningpoint", 0.75),
    (r"(?<![a-z])pence(?![a-z])", 0.65),   # avoid "Spencer", "defence", etc.
    (r"desantis", 0.75),
    (r"ron_?desantis", 0.8),
    (r"mtgreene", 0.85),
    # "marjorie" removed — common first name; mtgreene covers the MTG signal
    (r"boebert", 0.85),
    (r"gaetz", 0.8),
    (r"rand_?paul", 0.7),
    (r"ted_?cruz", 0.75),
    (r"vote_?red", 0.85),
    (r"voteredwave", 0.85),
    (r"redwave", 0.8),
    (r"trump2020", 0.95),
    (r"trump2024", 0.95),
    (r"trump_?train", 0.9),
    (r"trumptrain", 0.9),
    (r"drainthe_?swamp", 0.9),
    (r"drainswamp", 0.9),
    (r"buildthe_?wall", 0.9),
    (r"buildwall", 0.9),
    (r"stolenelection", 0.9),
    (r"stopthesteal", 0.9),
    (r"fakemedia", 0.8),
    (r"fakenews", 0.75),
    (r"fake_?news", 0.75),
    (r"msm_?lies", 0.8),
    (r"woke_?mob", 0.8),
    (r"anti_?woke", 0.8),
    (r"antiwoke", 0.8),
    (r"notmywoke", 0.75),
    (r"groomer", 0.75),
    (r"anti_?crt", 0.8),
    (r"anticrt", 0.8),
    (r"backtheblue", 0.7),
    (r"back_?the_?blue", 0.7),
    (r"thinblueline", 0.65),
    (r"blue_?lives", 0.7),

    # Strong liberal/progressive signals
    (r"bernie", -0.75),
    (r"bernie2020", -0.9),
    (r"bernie2024", -0.9),
    (r"sanders2020", -0.85),
    (r"feelthebern", -0.9),
    (r"feel_?the_?bern", -0.9),
    (r"(?<![a-z])aoc(?![a-z])", -0.8),  # avoid embedded: "caocao", "estaocupado"
    (r"ocasio", -0.8),
    (r"ocasio_?cortez|cortez_?ocasio", -0.8),  # avoid bare "cortez" (common Spanish surname)
    (r"warren2020", -0.85),
    (r"elizabethwarren", -0.8),
    (r"progressive", -0.7),
    (r"socialist", -0.8),
    (r"socialism", -0.8),
    (r"dem_?voter", -0.8),
    (r"vote_?blue", -0.85),
    (r"voteblue", -0.85),
    (r"blue_?wave", -0.8),
    (r"bluewave", -0.8),
    (r"democrat\d", -0.7),
    (r"trump(?:sa?|_?is_?a?)(?:douche|idiot|moron|loser|clown|sucks?|trash|liar|ass)", -0.85),  # anti-trump mockery suffixes
    (r"resist_?trump", -0.9),
    (r"resisttrump", -0.9),
    (r"anti_?trump", -0.85),
    (r"antitrump", -0.85),
    (r"no_?trump", -0.8),
    (r"dump_?trump", -0.9),
    (r"dumptrump", -0.9),
    (r"impeach_?trump", -0.9),
    (r"impeachtrump", -0.9),
    (r"the_?resistance", -0.8),
    (r"resist45", -0.9),
    (r"notmypresident", -0.85),
    (r"not_?my_?president", -0.85),
    (r"antifa", -0.8),
    (r"blm\d", -0.7),
    (r"blacklivesmatter", -0.75),
    (r"black_?lives", -0.6),
    (r"defund_?police", -0.85),
    (r"defundpolice", -0.85),
    (r"(?<![a-z])acab(?![a-z])", -0.8),  # avoid embedded: "alpacabinladen", "chupacabro"
    (r"abolish_?police", -0.85),
    (r"leftist", -0.75),
    (r"leftwin", -0.75),
    (r"left_?wing", -0.75),
    (r"dsa_?member", -0.85),      # Democratic Socialists of America
    (r"dsa\d", -0.7),
    (r"jacobin", -0.7),
    (r"peoples_?party", -0.7),
    (r"green_?party", -0.75),
    (r"jill_?stein", -0.7),
    (r"hillary2016", -0.8),
    (r"imwithher", -0.8),
    (r"(?<![a-z])obama", -0.5),
    (r"obamacares", -0.5),
    (r"obamacare", -0.5),
    (r"climate_?activist", -0.75),
    (r"climateactivist", -0.75),
    (r"pro_?choice", -0.8),
    (r"prochoice", -0.8),
    (r"abortion_?rights", -0.8),
    (r"roe_?v_?wade", -0.75),
    (r"feminazi", -0.7),
    (r"feminist\d", -0.6),
    (r"she_?her", -0.5),
    (r"they_?them", -0.5),
    (r"nonbinary", -0.5),
    (r"trans_?rights", -0.75),
    (r"transrights", -0.75),
    (r"lgbtq_?ally", -0.7),
    (r"lgbtqally", -0.7),
    (r"gay_?rights", -0.65),
    (r"love_?wins", -0.6),
    (r"equality_?now", -0.65),
    (r"squad_?forever", -0.8),  # The Squad (progressive congress members)
    (r"thesquad", -0.75),
    (r"ilhan_?omar", -0.8),
    (r"rashida_?tlaib", -0.8),
    (r"ayanna", -0.6),
    (r"(?<![a-z])woke", -0.5),      # avoid "awoke", "awoken"
    (r"woke\d", -0.6),
    (r"stay_?woke", -0.65),
    (r"staywoke", -0.65),
    (r"taxtherich", -0.75),
    (r"tax_?the_?rich", -0.75),
    (r"eattherich", -0.7),
    (r"eat_?the_?rich", -0.7),
    (r"(?<![a-z\d])m4a(?![a-z\d])", -0.7),  # Medicare for All; avoid embedded: "freedom4all", "swim4alife"
    (r"medicare_?for_?all", -0.75),
    (r"medicareforall", -0.75),
    (r"ubi_?now", -0.7),
    (r"gnd_?", -0.7),            # Green New Deal
    (r"green_?new_?deal", -0.75),
    (r"greennewdeal", -0.75),
    (r"msnbc_?fan", -0.65),
    (r"cnn_?viewer", -0.5),
    (r"rachel_?maddow", -0.7),
    (r"rfk_?jr", -0.4),         # ambiguous but slightly left-coded on reddit
]

# Compile patterns once
COMPILED_RULES: list[tuple[re.Pattern, float]] = [
    (re.compile(pattern, re.IGNORECASE), score)
    for pattern, score in KEYWORD_RULES
]


def score_username(username: str) -> float:
    lower = username.lower()
    matched_scores: list[float] = []
    for pattern, score in COMPILED_RULES:
        if pattern.search(lower):
            matched_scores.append(score)
    if not matched_scores:
        return 0.0
    # Average all matched signals, then clip to [-1, 1]
    avg = sum(matched_scores) / len(matched_scores)
    return round(max(-1.0, min(1.0, avg)), 4)


def main():
    input_path = "/Users/paulterrasi/Documents/Political-Signaling-Sentiment-Analysis/src/data_processing/convokit_corpus/all_usernames.csv"
    output_path = "/Users/paulterrasi/Documents/Political-Signaling-Sentiment-Analysis/src/data_processing/convokit_corpus/all_usernames_scored.csv"

    print("Scoring usernames...", flush=True)
    total = 0
    nonzero = 0

    with open(input_path, newline="", encoding="utf-8") as infile, \
         open(output_path, "w", newline="", encoding="utf-8") as outfile:

        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["username", "score"])

        for row in reader:
            username = row["username"]
            score = score_username(username)
            writer.writerow([username, score])
            total += 1
            if score != 0.0:
                nonzero += 1
            if total % 500_000 == 0:
                print(f"  {total:,} processed, {nonzero:,} non-zero ({100*nonzero/total:.2f}%)", flush=True)

    print(f"\nDone. {total:,} total, {nonzero:,} non-zero ({100*nonzero/total:.2f}%)")
    print(f"Output: {output_path}")


if __name__ == "__main__":
    main()
